# Configuración del servidor
server.port=9090


# Configuración de la base de datos (PostgreSQL en Docker)
# Nota: Si tu app corre fuera de Docker, usa 'localhost'.
# Si tu app también está dockerizada, usa el nombre del servicio de la red de Docker.
spring.datasource.url=jdbc:postgresql://localhost:5432/sakurapp
spring.datasource.username=postgres
spring.datasource.password=123
spring.datasource.driverClassName=org.postgresql.Driver

# Configuración de JPA / Hibernate
spring.jpa.database=postgresql
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Propiedad adicional para ver parámetros en los logs (opcional pero útil)
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
